### ISSUE TITLE
Cannot Find Notification Dropdown and User Button in Mobile View

### ISSUE THREAD

**Issue by Vbboi24** [mechevarria/patternfly-ng-seed#1]
Hey Great Repo to start with Patternfly,
It would be great if you could also show Notification in the Navbar during a Mobile View just like How Patternfly HTML Repo has

**Comment by mechevarria** [comment]
Yeah I noticed the issue too.  Did you find an example where notifications (the top right menu) was still accessible in mobile view?  I tried this link but the notifications are hidden when you toggle mobile view

[https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation-without-icons.html](https://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation-without-icons.html)

**Comment by mechevarria** [comment]
I just saw that the menu items get added to the bottom of the nav.  I'm asking to see how to show those items in the Patternfly-NG implementation

**Comment by mechevarria** [comment]
So the patternfly-ng maintainers are planning on implementing a mobileState check.  In the meantime they suggested manually checking for mobile state. I have an example done with the logout menu but not notifications yet

[https://github.com/mechevarria/patternfly-ng-seed/blob/master/src/app/nav/nav.component.ts](https://github.com/mechevarria/patternfly-ng-seed/blob/master/src/app/nav/nav.component.ts)

**Comment by Vbboi24** [comment]
Oh Wow, Cool. You are so Awesome !!

Thanks I have been breaking my head on this. Sorry for late reply too. I am trying to build a login component before the Home Component, but with the <app-nav> being the entry point in the app.component.html.
Trying to figure out a workaround
